### ISSUE TITLE
MDS Fest 2023 video recording

### ISSUE THREAD

**Issue by The-Pavel** [nicholasyager/overgrown-to-thriving#1]
Hello @nicholasyager, hope you are well!

I really enjoyed your talk at MDS Fest 2023 and was wondering if you have the recording of it? Sadly it seems to not be on the hopin.com platform that was hosting the event.

Hoping to rewatch your talk and share it with the team! Thank you in advance!

**Comment by nicholasyager** [comment]
Hi @The-Pavel! It looks like the recording _just_ made its way to YouTube. Here's a link: https://www.youtube.com/watch?v=bV7aLRocQdw
